/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Platform_Types.h"

#define RCC_BASE 				0x40021000
#define GPIO_PORTA				0x40010800
#define RCC_APB2ENR 		*(volatile uint32*)(0x40021018)
#define GPIO_PORTA_CRH		*(volatile uint32*)(0x40010804)
#define GPIO_PORTA_ODR		*(volatile uint32*)(0x4001080C)

#define IAOPEN 	(1<<2);
#define PIN13	(1UL<<13);

int main(void)
{
	RCC_APB2ENR|=IAOPEN;
	GPIO_PORTA_CRH&=0xFF0FFFFF;

	GPIO_PORTA_CRH|=0x00200000;
	/* Loop forever */
	while(1)
	{
		GPIO_PORTA_ODR|=(1<<13); //toggle
		int i=15;
		i++;
		for(i=0;i<700;i++)
		{

		}
		GPIO_PORTA_ODR&=~(1<<13);
		for(i=0;i<700;i++)
		{

		}


		/*	for(int i=0;i<1000;i++)
		{

		}
		GPIO_PORTA_ODR&=~PIN13;
		for(int i=0;i<1000;i++)
		{

		}*/

		//for(int i=0;i<5000;i++);//Delay loop
		/*while(cntr<5000)
		{
			cntr++;
		}
		cntr=0;*/

	}
}
