/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Platform_Types.h"

#define RCC_BASE 				0x40021000
#define GPIO_PORTA				0x40010800


#define RCC_APB2ENR 		*(volatile uint32*)(0x40021018)
#define RCC_CFGR			*(volatile uint32*)(RCC_BASE+0x04)
#define GPIO_PORTA_CRH		*(volatile uint32*)(0x40010804)
#define GPIO_PORTA_ODR		*(volatile uint32*)(0x4001080C)

#define IAOPEN 	(1<<2);
#define PIN13	(1UL<<13);



void clock_init()
{
	//By default HSI clock is enabled
	/*
	*1-Divide 8 MHZ sysclk by 2 for APB1
	*2-Divide 8 MHZ sysclk by 4 for APB2
	*3-AHB frequency 8 MHZ
	*4-Enable GPIO PORTA peripheral Clock 
	*/

	/*Bits 13:11 PPRE2: APB high-speed prescaler (APB2)
	Set and cleared by software to control the division factor of the APB high-speed clock
	(PCLK2).
	0xx: HCLK not divided
	100: HCLK divided by 2
	101: HCLK divided by 4
	110: HCLK divided by 8
	111: HCLK divided by 16*/
	RCC_CFGR|=(0b101<<11);

	/*Bits 10:8 PPRE1: APB low-speed prescaler (APB1)
	Set and cleared by software to control the division factor of the APB low-speed clock
	(PCLK1).
	Warning: the software has to set correctly these bits to not exceed 36 MHz on this domain
	0xx: HCLK not divided
	100: HCLK divided by 2
	101: HCLK divided by 4
	110: HCLK divided by 8
	111: HCLK divided by 16*/
	RCC_CFGR|=(0b100<<8);


}

int main(void)
{
	clock_init();
	RCC_APB2ENR|=IAOPEN;
	GPIO_PORTA_CRH&=0xFF0FFFFF;

	GPIO_PORTA_CRH|=0x00200000;
	/* Loop forever */
	while(1)
	{
		GPIO_PORTA_ODR|=(1<<13); //toggle
		int i=15;
		i++;
		for(i=0;i<700;i++)
		{

		}
		GPIO_PORTA_ODR&=~(1<<13);
		for(i=0;i<700;i++)
		{

		}


		/*	for(int i=0;i<1000;i++)
		{

		}
		GPIO_PORTA_ODR&=~PIN13;
		for(int i=0;i<1000;i++)
		{

		}*/

		//for(int i=0;i<5000;i++);//Delay loop
		/*while(cntr<5000)
		{
			cntr++;
		}
		cntr=0;*/

	}
}
